# Simplified Cloud Build configuration for Cosmo Backend
steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-west1-docker.pkg.dev/$PROJECT_ID/cosmo-docker/cosmo-api:latest'
      - '.'
    timeout: '600s'

  # Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-west1-docker.pkg.dev/$PROJECT_ID/cosmo-docker/cosmo-api:latest'
    timeout: '300s'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cosmo-backend'
      - '--image'
      - 'us-west1-docker.pkg.dev/$PROJECT_ID/cosmo-docker/cosmo-api:latest'
      - '--region'
      - 'us-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--concurrency'
      - '100'
      - '--timeout'
      - '60'
      - '--set-env-vars'
      - 'NODE_ENV=production,PROJECT_ID=$PROJECT_ID'
    timeout: '300s'

# Build configuration options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Timeout for entire build
timeout: '1200s'

# Tags for filtering builds
tags:
  - 'cosmo-backend'
  - 'cloud-run'